### ISSUE TITLE
Add unit tests

### ISSUE THREAD

**Issue by prestwich** [storj/storj-python-sdk#14]

**Comment by frdwrd** [comment]
I need to learn more about unittest.mock to do this properly.

**Comment by steenzout** [comment]
do you want me to implement one case?
after that it should be copy+paste.

**Comment by steenzout** [comment]
the latest merge has more examples of how to use `mock`.

**Comment by frdwrd** [comment]
Unit tests not implemented for http.py:
`file_upload`
`file_download`
`key_generate`
`key_import`

**Comment by steenzout** [comment]
link to this project [coveralls](https://coveralls.io/github/Storj/storj-python-sdk) where we can easily find where coverage is missing.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
