### ISSUE TITLE
Use better source of randomness

### ISSUE THREAD

**Issue by prestwich** [storj/storj-python-sdk#38]
Best practices suggest `os.urandom` or `random.SystemRandom`

**Comment by steenzout** [comment]
[reference](https://mail.python.org/pipermail/python-ideas/2015-September/035886.html)

**Comment by Miskerest** [comment]
Is this in reference to `_get_random_challenge_string`?

**Comment by steenzout** [comment]
I think so.

**Comment by frdwrd** [comment]
Yeah that's what brought it to my attention. I noticed a few other places where we could use non-reproducible randomness, like in `Keyring`.

**Comment by Miskerest** [comment]
Okay, I think this was fixed in the last commit but I'll leave it open as a reminder to use `os.urandom` in te future like in `Keyring` as @frdwrd mentioned.

**Comment by RichardLitt** [comment]
👋 Hey! Thanks for this contribution. Apologies for the delay in responding!

We've decided to rearchitect Storj, so that we can scale better. You can read more about this decision [here](https://storj.io/blog/2018/01/getting-from-petabytes-to-exabytes-the-road-ahead/). This means that we are entirely focused on v3 at the moment, in the [storj/storj](https://github.com/storj/storj) repository. Our white paper for v3 is coming **very, very** soon - follow along on [the blog](https://storj.io/blog) and in our [Rocketchat](https://community.storj.io/home).

As this repository is part of the v2 network, we're no longer maintaining this repository. I am going to close this for now. If you have any questions, I encourage you to jump on Rocketchat and ask them there. Thanks!
